apiVersion: v2
name: nginx    #name of the chart 
version: 0.0.2  #This is chart version
appVersion: latest # This is the version of the app thet this contains (like catalogue verssion)
description: "upgrading to latest "
