apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx
  labels:
    project: roboshop
    tier: frontend
    component: frontend
  annotations:
    kubernetes.io/change-cause: {{ .Values.deployment.change-cause }} 
spec:
  replicas: {{ .Values.deployment.replicas }}
  selector:
    matchLabels:
      project: roboshop
      tier: frontend
      component: frontend  
  template:
    metadata:
      labels:
        project: roboshop
        tier: frontend
        component: frontend  
    spec:
      containers:
        - name: nginx 
          image: {{ .Values.deployment.imageVersion }}

